
services:
    # mysql
    db80:
      image: mysql:8.0
      platform: linux/x86_64
      container_name: mysql80-development
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE:-db_example}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
      ports:
        - "3002:3306"
      networks:
        - development-network

    # postgres
    postgres:
      image: postgres:15-alpine
      container_name: postgres-development
      environment:
        POSTGRES_DB: laravel
        POSTGRES_USER: laravel_user
        POSTGRES_PASSWORD: secret
      ports:
        - "6001:5432"
      volumes:
        - postgredev:/var/lib/postgresql/data
      networks:
        - development-network

    # mongo
    mongo:
      image: mongo:8.0.4-noble
      container_name: mongo-development
      ports:
        - "21011:27017"
      volumes:
        - mongodev:/data/db
      networks:
        - development-network

networks:
  development-network:
    external: true

volumes:
  postgredev:
  mongodev:

  db.createUser({
user: “development”,
pwd: “secret”,
roles: [ { role: "root", db: "admin" } ]
});